### ISSUE TITLE
Git usage

### ISSUE THREAD

**Issue by Lonami** [vzccristian/pyro4bot#4]
`git` is a powerful tool, but one must know how to use it. It enforces developers to write a commit message not without a reason, it's *very* important to know the changes introduced by a commit without the need to read potentially hundreds of lines. This is why writing short and useful commit messages is important. If the commit messages are "fixes", "working", "sockets" and so on, that's nearly as useful as versioning the project with `.zip` files instead. A mess.

Branches are also powerful if used correctly, and they should have **descriptive names** as well. Currently there's `developing`, `a_developing` and `c_developing` with "This branch is 14 commits ahead, 13 commits behind developing.". Why did it diverge so much, and why hasn't the work been done in `developing` too? What features is each branch working on? Again, current commit messages don't help much.

While you should take the advices described here with a grain on salt, the https://chris.beams.io/posts/git-commit/ article is a good read on how to write `git` messages properly, and in a consistent way.

**Comment by vzccristian** [comment]
Hi Lonami,

This project is currently under development. There is a great divergence between "c_developing" and developing because they are different versions and improvements regarding the same issue. For example, "c_developing" is my branch of work. As we are in initial versions, only these branches exist to be able to work autonomously with respect to the other branch. 

In the same way, commit messages are not very descriptive because the changes are not great. 

Soon, when the project is structured and planned, the commits and the names of the branches will be well defined.

Thank you very much for your help.

Regards,
Cristian

**Comment by Lonami** [comment]
> There is a great divergence between "c_developing" and developing because they are different versions and improvements regarding the same issue.

If branches diverge this much, they should be different projects! A branch should focus on a new feature, or a somewhat large bug fix. If it's just another commit, there's no need to make a branch. Every can push and pull from the same branch, `developing` if you wish to keep `master` clean. Personally I find a `developing` branch unnecessary, and just use tags when the project reaches a stable version.

> commit messages are not very descriptive because the changes are not great.

That can never be an excuse. You can always make a small change, or a somewhat big one related to a single thing (style issues, renaming files, etc.). And since they're only affecting a certain topic, the commit message can just refer to said topic, instead combining "done this, this and that".

**Comment by vzccristian** [comment]
> If branches diverge this much, they should be different projects! A branch should focus on a new feature, or a somewhat large bug fix. If it's just another commit, there's no need to make a branch. Every can push and pull from the same branch, developing if you wish to keep master clean. Personally I find a developing branch unnecessary, and just use tags when the project reaches a stable version.

I think I have not expressed myself well. Yes, it could be in two different projects but it is the same project in test mode, these branches are merely organizational.

I insist that we are test mode. We may not use GIT in the most appropriate way, but it is not essential now. We use GIT as we need at this time.

> That can never be an excuse. You can always make a small change, or a somewhat big one related to a single thing (style issues, renaming files, etc.). And since they're only affecting a certain topic, the commit message can just refer to said topic, instead combining "done this, this and that".

Suppose, you have been working on something but it is not working yet. You do not know if it will work. You upload the code for a variety of reasons:

1. So that another collaborator can see it and can help you.
2. Simply because you will continue working later, perhaps on another computer.
3. Versions

I understand what you mean by your report, but sometimes things are not used for what has been designed but for what is needed.

**Comment by Lonami** [comment]
> We may not use GIT in the most appropriate way, but it is not essential now.

It *always* is essential! If anyone ever wants to find when a bug could have been introduced, or easily follow the evolution of the project, or review a commit, it's really hard if they're this large!

> do not know if it will work.

Then you make a branch called `feature-x` and work **only** on that feature. If you're gonna fix something else, you switch back and forth to the `developing` branch. And once such experimental feature is tested, reviewed and it works, it can be merged. All the points you've given, sure! But keep the branch on topic, and give it a descriptive name.

> sometimes things are not used for what has been designed but for what is needed.

The case you've described is covered by the use of branches as I said, but when used properly. It's what was designed, and what you need.
